select FI.ID, FNI.FISH_NAME, FI.LENGTH
from FISH_INFO FI
join FISH_NAME_INFO FNI on FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN
(
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
order by FI.ID ASC